
# Cấu hình Codemagic CI/CD cho Xổ Số Kim Tiền
workflows:
  react-web-workflow:
    name: React Web Build & Deploy
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: latest
      npm: latest
      groups:
        - api_keys
      vars:
        PUBLIC_URL: "https://xoso-kimtien.web.app"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build React App
        script: |
          # Xây dựng ứng dụng bằng Vite
          npm run build
    artifacts:
      - build/**
    publishing:
      email:
        recipients:
          - tonyhoaivu@gmail.com
